-- MySQL Script generated by MySQL Workbench
-- Thursday 02 June 2016 09:52:13 PM IST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema raincatc_new_portal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema raincatc_new_portal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `raincatc_new_portal` DEFAULT CHARACTER SET utf8 ;
USE `raincatc_new_portal` ;

-- -----------------------------------------------------
-- Table `raincatc_new_portal`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `raincatc_new_portal`.`users` ;

CREATE TABLE IF NOT EXISTS `raincatc_new_portal`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `profile_pic` VARCHAR(45) NULL,
  `type` VARCHAR(45) NOT NULL,
  `status` TINYINT(1) NOT NULL,
  `passwd_change_token` VARCHAR(45) NULL,
  `accept_terms` TINYINT(1) NULL DEFAULT 0,
  `deleted_at` DATETIME NULL,
  `created_by` INT NULL,
  `updated_by` INT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `raincatc_new_portal`.`professions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `raincatc_new_portal`.`professions` ;

CREATE TABLE IF NOT EXISTS `raincatc_new_portal`.`professions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `deleted_at` DATETIME NULL,
  `created_by` INT NULL,
  `updated_by` INT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `raincatc_new_portal`.`industries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `raincatc_new_portal`.`industries` ;

CREATE TABLE IF NOT EXISTS `raincatc_new_portal`.`industries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `deleted_at` DATETIME NULL,
  `created_by` INT NULL,
  `updated_by` INT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `raincatc_new_portal`.`jobs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `raincatc_new_portal`.`jobs` ;

CREATE TABLE IF NOT EXISTS `raincatc_new_portal`.`jobs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `industry_id` INT NOT NULL,
  `profession_id` INT NOT NULL,
  `skills` VARCHAR(75) NULL,
  `job_location` VARCHAR(45) NOT NULL,
  `position_type` VARCHAR(45) NOT NULL,
  `client_name` VARCHAR(45) NOT NULL,
  `client_name_confidential` TINYINT(1) NOT NULL,
  `salary` VARCHAR(45) NULL,
  `payment_terms` VARCHAR(45) NULL,
  `note` TEXT NULL,
  `description` TEXT NULL,
  `warranty_period` VARCHAR(45) NULL,
  `split_percentage` VARCHAR(45) NULL,
  `user_id` INT NOT NULL,
  `status` TINYINT(1) NULL DEFAULT 0,
  `closed` TINYINT(1) NOT NULL DEFAULT 0,
  `deleted_at` DATETIME NULL,
  `created_by` INT NULL,
  `updated_by` INT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_jobs_users1_idx` (`user_id` ASC),
  INDEX `fk_jobs_professions1_idx` (`profession_id` ASC),
  INDEX `fk_jobs_industries1_idx` (`industry_id` ASC),
  CONSTRAINT `fk_jobs_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `raincatc_new_portal`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jobs_professions1`
    FOREIGN KEY (`profession_id`)
    REFERENCES `raincatc_new_portal`.`professions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jobs_industries1`
    FOREIGN KEY (`industry_id`)
    REFERENCES `raincatc_new_portal`.`industries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `raincatc_new_portal`.`accepted_jobs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `raincatc_new_portal`.`accepted_jobs` ;

CREATE TABLE IF NOT EXISTS `raincatc_new_portal`.`accepted_jobs` (
  `user_id` INT NOT NULL,
  `job_id` INT NOT NULL,
  INDEX `fk_users_has_jobs_jobs1_idx` (`job_id` ASC),
  INDEX `fk_users_has_jobs_users1_idx` (`user_id` ASC),
  PRIMARY KEY (`user_id`, `job_id`),
  CONSTRAINT `fk_users_has_jobs_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `raincatc_new_portal`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_jobs_jobs1`
    FOREIGN KEY (`job_id`)
    REFERENCES `raincatc_new_portal`.`jobs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `raincatc_new_portal`.`candidates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `raincatc_new_portal`.`candidates` ;

CREATE TABLE IF NOT EXISTS `raincatc_new_portal`.`candidates` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `employment_history` TEXT NULL,
  `notes` TEXT NULL,
  `resume` VARCHAR(45) NULL,
  `user_id` INT NOT NULL,
  `job_id` INT NOT NULL,
  `client_accepted` TINYINT(1) DEFAULT 0,
  `hired` TINYINT(1) NULL,
  `start_date` DATE NULL,
  `base_salary` FLOAT NULL,
  `additional_info` TEXT NULL,
  `deleted_at` DATETIME NULL,
  `created_by` INT NULL,
  `updated_by` INT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_candidates_users1_idx` (`user_id` ASC),
  INDEX `fk_candidates_jobs1_idx` (`job_id` ASC),
  CONSTRAINT `fk_candidates_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `raincatc_new_portal`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_candidates_jobs1`
    FOREIGN KEY (`job_id`)
    REFERENCES `raincatc_new_portal`.`jobs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `raincatc_new_portal`.`candidate_feedback`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `raincatc_new_portal`.`candidate_feedback` ;

CREATE TABLE IF NOT EXISTS `raincatc_new_portal`.`candidate_feedback` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `candidate_id` INT NOT NULL,
  `feedback` TEXT NULL,
  `deleted_at` DATETIME NULL,
  `created_by` INT NULL,
  `updated_by` INT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  INDEX `fk_users_has_candidates_candidates1_idx` (`candidate_id` ASC),
  INDEX `fk_users_has_candidates_users1_idx` (`user_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_users_has_candidates_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `raincatc_new_portal`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_candidates_candidates1`
    FOREIGN KEY (`candidate_id`)
    REFERENCES `raincatc_new_portal`.`candidates` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `raincatc_new_portal`.`recruiter_notes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `raincatc_new_portal`.`recruiter_notes` ;

CREATE TABLE IF NOT EXISTS `raincatc_new_portal`.`recruiter_notes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `candidate_id` INT NOT NULL,
  `feedback` TEXT NULL,
  `deleted_at` DATETIME NULL,
  `created_by` INT NULL,
  `updated_by` INT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  INDEX `fk_users_has_candidates_candidates2_idx` (`candidate_id` ASC),
  INDEX `fk_users_has_candidates_users2_idx` (`user_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_users_has_candidates_users2`
    FOREIGN KEY (`user_id`)
    REFERENCES `raincatc_new_portal`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_candidates_candidates2`
    FOREIGN KEY (`candidate_id`)
    REFERENCES `raincatc_new_portal`.`candidates` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `raincatc_new_portal`.`states`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `raincatc_new_portal`.`states` ;

CREATE TABLE IF NOT EXISTS `raincatc_new_portal`.`states` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `abbreviation` VARCHAR(5) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `raincatc_new_portal`.`user_profiles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `raincatc_new_portal`.`user_profiles` ;

CREATE TABLE IF NOT EXISTS `raincatc_new_portal`.`user_profiles` (
  `user_id` INT NOT NULL,
  `company_address` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `state_id` INT NULL,
  `zipcode` VARCHAR(45) NULL,
  `linkedin_url` VARCHAR(45) NULL,
  `company_name` VARCHAR(45) NULL,
  `company_desc` TEXT NULL,
  `company_website_url` VARCHAR(45) NULL,
  `role` VARCHAR(45) NULL,
  `created_by` INT NULL,
  `updated_by` INT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_user_profiles_users1_idx` (`user_id` ASC),
  INDEX `fk_user_profiles_states1_idx` (`state_id` ASC),
  CONSTRAINT `fk_user_profiles_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `raincatc_new_portal`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_profiles_states1`
    FOREIGN KEY (`state_id`)
    REFERENCES `raincatc_new_portal`.`states` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `raincatc_new_portal`.`mails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `raincatc_new_portal`.`mails` ;

CREATE TABLE IF NOT EXISTS `raincatc_new_portal`.`mails` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `to` VARCHAR(45) NULL,
  `from` VARCHAR(45) NULL,
  `subject` VARCHAR(45) NULL,
  `body` TEXT NULL,
  `sent` TINYINT(1) NULL DEFAULT 0,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `raincatc_new_portal`.`rejected_jobs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `raincatc_new_portal`.`rejected_jobs` ;

CREATE TABLE IF NOT EXISTS `raincatc_new_portal`.`rejected_jobs` (
  `user_id` INT NOT NULL,
  `job_id` INT NOT NULL,
  INDEX `fk_users_has_jobs_jobs1_idx` (`job_id` ASC),
  INDEX `fk_users_has_jobs_users1_idx` (`user_id` ASC),
  PRIMARY KEY (`user_id`, `job_id`),
  CONSTRAINT `fk_users_has_jobs_users10`
    FOREIGN KEY (`user_id`)
    REFERENCES `raincatc_new_portal`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_jobs_jobs10`
    FOREIGN KEY (`job_id`)
    REFERENCES `raincatc_new_portal`.`jobs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `raincatc_new_portal`.`candidate_documents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `raincatc_new_portal`.`candidate_documents` ;

CREATE TABLE IF NOT EXISTS `raincatc_new_portal`.`candidate_documents` (
  `id` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `file_path` VARCHAR(45) NULL,
  `candidate_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_candidate_documents_candidates1_idx` (`candidate_id` ASC),
  CONSTRAINT `fk_candidate_documents_candidates1`
    FOREIGN KEY (`candidate_id`)
    REFERENCES `raincatc_new_portal`.`candidates` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `raincatc_new_portal`.`industry_profession`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `raincatc_new_portal`.`industry_profession` ;

CREATE TABLE IF NOT EXISTS `raincatc_new_portal`.`industry_profession` (
  `profession_id` INT NOT NULL,
  `industry_id` INT NOT NULL,
  PRIMARY KEY (`profession_id`, `industry_id`),
  INDEX `fk_professions_has_industries_industries1_idx` (`industry_id` ASC),
  INDEX `fk_professions_has_industries_professions1_idx` (`profession_id` ASC),
  CONSTRAINT `fk_professions_has_industries_professions1`
    FOREIGN KEY (`profession_id`)
    REFERENCES `raincatc_new_portal`.`professions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_professions_has_industries_industries1`
    FOREIGN KEY (`industry_id`)
    REFERENCES `raincatc_new_portal`.`industries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `raincatc_new_portal`.`profession_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `raincatc_new_portal`.`profession_user` ;

CREATE TABLE IF NOT EXISTS `raincatc_new_portal`.`profession_user` (
  `user_id` INT NOT NULL,
  `profession_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `profession_id`),
  INDEX `fk_users_has_professions_professions1_idx` (`profession_id` ASC),
  INDEX `fk_users_has_professions_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_users_has_professions_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `raincatc_new_portal`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_professions_professions1`
    FOREIGN KEY (`profession_id`)
    REFERENCES `raincatc_new_portal`.`professions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `raincatc_new_portal`.`industry_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `raincatc_new_portal`.`industry_user` ;

CREATE TABLE IF NOT EXISTS `raincatc_new_portal`.`industry_user` (
  `user_id` INT NOT NULL,
  `industry_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `industry_id`),
  INDEX `fk_users_has_industries_industries1_idx` (`industry_id` ASC),
  INDEX `fk_users_has_industries_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_users_has_industries_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `raincatc_new_portal`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_industries_industries1`
    FOREIGN KEY (`industry_id`)
    REFERENCES `raincatc_new_portal`.`industries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `raincatc_new_portal`.`preferred_agencies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `raincatc_new_portal`.`preferred_agencies` ;

CREATE TABLE IF NOT EXISTS `raincatc_new_portal`.`preferred_agencies` (
  `user_id` INT NOT NULL,
  `agency_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `agency_id`),
  INDEX `fk_users_has_users_users2_idx` (`agency_id` ASC),
  INDEX `fk_users_has_users_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_users_has_users_users1`
  FOREIGN KEY (`user_id`)
    REFERENCES `raincatc_new_portal`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_users_users2`
    FOREIGN KEY (`agency_id`)
    REFERENCES `raincatc_new_portal`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `raincatc_new_portal`.`rating`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `raincatc_new_portal`.`rating` ;

CREATE TABLE IF NOT EXISTS `raincatc_new_portal`.`rating` (
  `user_id` INT NOT NULL,
  `agency_id` INT NOT NULL,
  `rating` INT NULL,
  `review` TEXT NULL,
  PRIMARY KEY (`user_id`, `agency_id`),
  INDEX `fk_users_has_users_users4_idx` (`agency_id` ASC),
  INDEX `fk_users_has_users_users3_idx` (`user_id` ASC),
  CONSTRAINT `fk_users_has_users_users3`
  FOREIGN KEY (`user_id`)
    REFERENCES `raincatc_new_portal`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_users_users4`
  FOREIGN KEY (`agency_id`)
    REFERENCES `raincatc_new_portal`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `raincatc_new_portal`.`users`
-- -----------------------------------------------------
START TRANSACTION;
USE `raincatc_new_portal`;
INSERT INTO `raincatc_new_portal`.`users` (`id`, `email`, `password`, `first_name`, `last_name`, `profile_pic`, `type`, `status`, `passwd_change_token`, `accept_terms`, `deleted_at`, `created_by`, `updated_by`, `created_at`, `updated_at`) VALUES (1, 'admin@rcportal.com', '0f359740bd1cda994f8b55330c86d845', 'Rohan', 'Patil', '', 'admin', 1, '', 1, '', 1, 1, '2016-05-19 06:18:16', '2016-05-19 06:18:16');

COMMIT;


-- -----------------------------------------------------
-- Data for table `raincatc_new_portal`.`states`
-- -----------------------------------------------------
START TRANSACTION;
USE `raincatc_new_portal`;
INSERT INTO `raincatc_new_portal`.`states` (`id`, `name`, `abbreviation`) VALUES (NULL, 'Alabama', 'AL');
INSERT INTO `raincatc_new_portal`.`states` (`id`, `name`, `abbreviation`) VALUES (NULL, 'Alaska', 'AK');
INSERT INTO `raincatc_new_portal`.`states` (`id`, `name`, `abbreviation`) VALUES (NULL, 'Arizona', 'AZ');
INSERT INTO `raincatc_new_portal`.`states` (`id`, `name`, `abbreviation`) VALUES (NULL, 'Arkansas', 'AR');
INSERT INTO `raincatc_new_portal`.`states` (`id`, `name`, `abbreviation`) VALUES (NULL, 'California', 'CA');
INSERT INTO `raincatc_new_portal`.`states` (`id`, `name`, `abbreviation`) VALUES (NULL, 'Colorado', 'CO');
INSERT INTO `raincatc_new_portal`.`states` (`id`, `name`, `abbreviation`) VALUES (NULL, 'Connecticut', 'CT');
INSERT INTO `raincatc_new_portal`.`states` (`id`, `name`, `abbreviation`) VALUES (NULL, 'Delaware', 'DE');
INSERT INTO `raincatc_new_portal`.`states` (`id`, `name`, `abbreviation`) VALUES (NULL, 'Florida', 'FL');
INSERT INTO `raincatc_new_portal`.`states` (`id`, `name`, `abbreviation`) VALUES (NULL, 'Georgia', 'GA');
INSERT INTO `raincatc_new_portal`.`states` (`id`, `name`, `abbreviation`) VALUES (NULL, 'Hawaii', 'HI');
INSERT INTO `raincatc_new_portal`.`states` (`id`, `name`, `abbreviation`) VALUES (NULL, 'Idaho', 'ID');
INSERT INTO `raincatc_new_portal`.`states` (`id`, `name`, `abbreviation`) VALUES (NULL, 'Illinois', 'IL');
INSERT INTO `raincatc_new_portal`.`states` (`id`, `name`, `abbreviation`) VALUES (NULL, 'Indiana', 'IN');
INSERT INTO `raincatc_new_portal`.`states` (`id`, `name`, `abbreviation`) VALUES (NULL, 'Iowa', 'IA');
INSERT INTO `raincatc_new_portal`.`states` (`id`, `name`, `abbreviation`) VALUES (NULL, 'Kansas', 'KS');
INSERT INTO `raincatc_new_portal`.`states` (`id`, `name`, `abbreviation`) VALUES (NULL, 'Kentucky', 'KY');
INSERT INTO `raincatc_new_portal`.`states` (`id`, `name`, `abbreviation`) VALUES (NULL, 'Louisiana', 'LA');
INSERT INTO `raincatc_new_portal`.`states` (`id`, `name`, `abbreviation`) VALUES (NULL, 'Maine', 'ME');
INSERT INTO `raincatc_new_portal`.`states` (`id`, `name`, `abbreviation`) VALUES (NULL, 'Maryland', 'MD');
INSERT INTO `raincatc_new_portal`.`states` (`id`, `name`, `abbreviation`) VALUES (NULL, 'Massachusetts', 'MA');
INSERT INTO `raincatc_new_portal`.`states` (`id`, `name`, `abbreviation`) VALUES (NULL, 'Michigan', 'MI');
INSERT INTO `raincatc_new_portal`.`states` (`id`, `name`, `abbreviation`) VALUES (NULL, 'Minnesota', 'MN');
INSERT INTO `raincatc_new_portal`.`states` (`id`, `name`, `abbreviation`) VALUES (NULL, 'Mississippi', 'MS');
INSERT INTO `raincatc_new_portal`.`states` (`id`, `name`, `abbreviation`) VALUES (NULL, 'Missouri', 'MO');
INSERT INTO `raincatc_new_portal`.`states` (`id`, `name`, `abbreviation`) VALUES (NULL, 'Montana', 'MT');
INSERT INTO `raincatc_new_portal`.`states` (`id`, `name`, `abbreviation`) VALUES (NULL, 'Nebraska', 'NE');
INSERT INTO `raincatc_new_portal`.`states` (`id`, `name`, `abbreviation`) VALUES (NULL, 'Nevada', 'NV');
INSERT INTO `raincatc_new_portal`.`states` (`id`, `name`, `abbreviation`) VALUES (NULL, 'New Hampshire', 'NH');
INSERT INTO `raincatc_new_portal`.`states` (`id`, `name`, `abbreviation`) VALUES (NULL, 'New Jersey', 'NJ');
INSERT INTO `raincatc_new_portal`.`states` (`id`, `name`, `abbreviation`) VALUES (NULL, 'New Mexico', 'NM');
INSERT INTO `raincatc_new_portal`.`states` (`id`, `name`, `abbreviation`) VALUES (NULL, 'New York', 'NY');
INSERT INTO `raincatc_new_portal`.`states` (`id`, `name`, `abbreviation`) VALUES (NULL, 'North Carolina', 'NC');
INSERT INTO `raincatc_new_portal`.`states` (`id`, `name`, `abbreviation`) VALUES (NULL, 'North Dakota', 'ND');
INSERT INTO `raincatc_new_portal`.`states` (`id`, `name`, `abbreviation`) VALUES (NULL, 'Ohio', 'OH');
INSERT INTO `raincatc_new_portal`.`states` (`id`, `name`, `abbreviation`) VALUES (NULL, 'Oklahoma', 'OK');
INSERT INTO `raincatc_new_portal`.`states` (`id`, `name`, `abbreviation`) VALUES (NULL, 'Oregon', 'OR');
INSERT INTO `raincatc_new_portal`.`states` (`id`, `name`, `abbreviation`) VALUES (NULL, 'Pennsylvania', 'PA');
INSERT INTO `raincatc_new_portal`.`states` (`id`, `name`, `abbreviation`) VALUES (NULL, 'Rhode Island', 'RI');
INSERT INTO `raincatc_new_portal`.`states` (`id`, `name`, `abbreviation`) VALUES (NULL, 'South Carolina', 'SC');
INSERT INTO `raincatc_new_portal`.`states` (`id`, `name`, `abbreviation`) VALUES (NULL, 'South Dakota', 'SD');
INSERT INTO `raincatc_new_portal`.`states` (`id`, `name`, `abbreviation`) VALUES (NULL, 'Tennessee', 'TN');
INSERT INTO `raincatc_new_portal`.`states` (`id`, `name`, `abbreviation`) VALUES (NULL, 'Texas', 'TX');
INSERT INTO `raincatc_new_portal`.`states` (`id`, `name`, `abbreviation`) VALUES (NULL, 'Utah', 'UT');
INSERT INTO `raincatc_new_portal`.`states` (`id`, `name`, `abbreviation`) VALUES (NULL, 'Vermont', 'VT');
INSERT INTO `raincatc_new_portal`.`states` (`id`, `name`, `abbreviation`) VALUES (NULL, 'Virginia', 'VA');
INSERT INTO `raincatc_new_portal`.`states` (`id`, `name`, `abbreviation`) VALUES (NULL, 'Washington', 'WA');
INSERT INTO `raincatc_new_portal`.`states` (`id`, `name`, `abbreviation`) VALUES (NULL, 'West Virginia', 'WV');
INSERT INTO `raincatc_new_portal`.`states` (`id`, `name`, `abbreviation`) VALUES (NULL, 'Wisconsin', 'WI');
INSERT INTO `raincatc_new_portal`.`states` (`id`, `name`, `abbreviation`) VALUES (NULL, 'Wyoming', 'WY');

COMMIT;

